Stream logs, and redirect to tarball when finished

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 set -e
+set -o pipefail
 
 RECIPE="$1"
 PREFIX=${PREFIX:="/usr/local"}
@@ -15,7 +16,7 @@ if [ -z "$LOGGER" ]; then rm -f /tmp/log; LOGGER=/tmp/log; fi
 
 rm -rf "$PREFIX" && mkdir -p "$PREFIX"
 if [ -f  "$SOURCE/recipes/$RECIPE" ]; then
-	if $SOURCE/recipes/$RECIPE "$PREFIX" &> $LOGGER ; then
+	if $SOURCE/recipes/$RECIPE "$PREFIX" 2>&1 | tee -a $LOGGER 1>&2 ; then
 		if [ -f $LOGGER ] ; then
 			cp $LOGGER "$PREFIX/buildcurl.log"
 		fi
@@ -23,8 +24,8 @@ if [ -f  "$SOURCE/recipes/$RECIPE" ]; then
 		finish 0
 	else
 		if [ -f $LOGGER ] ; then
-			echo "-----> BUILD FAILED, please see the details below:"
-			cat $LOGGER
+			echo "-----> BUILD FAILED, please see the details below:" 1>&2
+			cat $LOGGER 1>&2
 		fi
 		finish 1
 	fi
